/**
 * Strong accomplishment-driven action verbs for resume bullets.
 * Prefer unique openers; never reuse the same verb more than twice across a resume.
 */
export const STRONG_ACTION_VERBS = [
  // Strong Accomplishment-driven
  "Accelerated",
  "Achieved",
  "Attained",
  "Completed",
  "Conceived",
  "Convinced",
  "Discovered",
  "Doubled",
  "Effected",
  "Eliminated",
  "Expanded",
  "Expedited",
  "Founded",
  "Improved",
  "Increased",
  "Initiated",
  "Innovated",
  "Introduced",
  "Invented",
  "Launched",
  "Mastered",
  "Overcame",
  "Overhauled",
  "Pioneered",
  "Reduced",
  "Resolved",
  "Revitalized",
  "Spearheaded",
  "Strengthened",
  "Transformed",
  "Upgraded",
  "Tripled",
  // Communication
  "Addressed",
  "Advised",
  "Arranged",
  "Authored",
  "Co-authored",
  "Co-ordinated",
  "Communicated",
  "Corresponded",
  "Counselled",
  "Developed",
  "Demonstrated",
  "Directed",
  "Drafted",
  "Enlisted",
  "Facilitated",
  "Formulated",
  "Guided",
  "Influenced",
  "Interpreted",
  "Interviewed",
  "Instructed",
  "Lectured",
  "Led",
  "Liaised",
  "Mediated",
  "Moderated",
  "Motivated",
  "Negotiated",
  "Persuaded",
  "Presented",
  "Promoted",
  "Proposed",
  "Publicized",
  "Recommended",
  "Reconciled",
  "Recruited",
  "Taught",
  "Trained",
  "Translated",
  // Entrepreneurial
  "Composed",
  "Created",
  "Designed",
  "Devised",
  "Established",
  "Generated",
  "Implemented",
  "Instituted",
  "Opened",
  "Originated",
  "Planned",
  "Prepared",
  "Produced",
  "Started",
  "Released",
  // Management
  "Administered",
  "Analyzed",
  "Assigned",
  "Chaired",
  "Consolidated",
  "Contracted",
  "Delegated",
  "Evaluated",
  "Executed",
  "Organized",
  "Prioritized",
  "Reorganized",
  "Reviewed",
  "Scheduled",
  "Supervised",
  "Managed",
  // Leadership / Mentorship / Teaching
  "Coached",
  "Conducted",
  "Illustrated",
  "Performed",
  "Mentored",
  "Awarded",
  "Revamped",
  "Allocated",
  "Assessed",
  "Clarified",
  "Counseled",
  "Diagnosed",
  "Educated",
  "Familiarized",
  "Referred",
  "Rehabilitated",
  "Reinforced",
  "Represented",
  "Verified",
  "Adapted",
  "Coordinated",
  "Enabled",
  "Encouraged",
  "Explained",
  "Informed",
  "Stimulated",
  // Research and Analysis
  "Classified",
  "Collated",
  "Defined",
  "Forecasted",
  "Identified",
  "Investigated",
  "Researched",
  "Tested",
  "Traced",
  "Uncovered",
  "Collected",
  "Critiqued",
  "Examined",
  "Extracted",
  "Inspected",
  "Inspired",
  "Summarized",
  "Surveyed",
  "Systemized",
  // Problem Solving
  "Budgeted",
  "Controlled",
  "Itemised",
  "Modernised",
  "Operated",
  "Organised",
  "Processed",
  "Redesigned",
  "Refined",
  "Revised",
  "Simplified",
  "Solved",
  "Streamlined",
  // Process Improvement / Consulting / Operations
  "Combined",
  "Converted",
  "Cut",
  "Decreased",
  "Minimised",
  "Restructured",
  "Saved",
  "Serviced",
  "Trimmed",
  "Unified",
  "Widened",
  "Broadened",
  // Financial
  "Appraised",
  "Audited",
  "Balanced",
  "Calculated",
  "Computed",
  "Projected",
  "Modelled",
  "Arbitrated",
  // Design and Creative
  "Acted",
  "Conceptualized",
  "Customized",
  "Fashioned",
  "Integrated",
  "Proved",
  "Set up",
  "Shaped",
  "Structured",
  "Tabulated",
  "Validated",
  // Clerical / Detail
  "Approved",
  "Catalogued",
  "Compiled",
  "Dispatched",
  "Monitored",
  "Ordered",
  "Purchased",
  "Recorded",
  "Retrieved",
  "Screened",
  "Specified",
  "Systematized",
  // Engineering / Technical
  "Coded",
  "Extrapolated",
  "Predicted",
  "Installed",
  "Engineered",
  "Segmented",
  "Estimated",
  "Assembled",
  "Visualized",
  "Debugged",
  "Standardized",
  "Steered",
  "Automated",
  "Troubleshooted",
  "Architected",
  "Deployed",
] as const;

/** Deduped lowercase set for quick lookups. */
export const STRONG_ACTION_VERB_SET = new Set(
  STRONG_ACTION_VERBS.map((v) => v.toLowerCase()),
);

export const WEAK_ACTION_VERBS = [
  "Helped",
  "Assisted",
  "Worked",
  "Responsible",
  "Supported",
  "Participated",
  "Handled",
  "Tasked",
] as const;

/** Compact list for LLM prompts (unique, stable order). */
export function actionVerbPromptList(): string {
  const unique: string[] = [];
  const seen = new Set<string>();
  for (const v of STRONG_ACTION_VERBS) {
    const key = v.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    unique.push(v);
  }
  return unique.join(", ");
}
